library( LatticeKrig)
source( "fig1DApprox.R")
setwd("~/Dropbox/Home/Current_talks/SARCarpentry")
pdf("pix/fig1DApproxA.pdf", height=6, width=6)
fields.style()
fig1DApprox(22, TRUE)
dev.off()
pdf("pix/fig1DApproxB.pdf", height=6, width=6)
fields.style()
fig1DApprox(22, FALSE)
dev.off()
